PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX vcard: <http://www.w3.org/2001/vcard-rdf/3.0#>

CONSTRUCT {
  ?person vcard:FN ?name .
  ?person vcard:EMAIL ?mbox .
}
WHERE {
  ?person foaf:name ?name .
  OPTIONAL { ?person foaf:mbox ?mbox . }
}
