/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 38
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 38
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_content_token1 = 1,
  anon_sym_LT = 2,
  anon_sym_LBRACK = 3,
  anon_sym_DOLLAR = 4,
  anon_sym_DOLLAR_LBRACE = 5,
  anon_sym_RBRACE = 6,
  sym_expression = 7,
  anon_sym_LT_POUND_DASH_DASH = 8,
  anon_sym_DASH_DASH_GT = 9,
  anon_sym_LBRACK_POUND_DASH_DASH = 10,
  anon_sym_DASH_DASH_RBRACK = 11,
  sym_comment_content = 12,
  anon_sym_LT_POUND = 13,
  anon_sym_LT_SLASH_POUND = 14,
  anon_sym_GT = 15,
  anon_sym_LBRACK_POUND = 16,
  anon_sym_LBRACK_SLASH_POUND = 17,
  anon_sym_RBRACK = 18,
  anon_sym_LT_AT = 19,
  anon_sym_LT_SLASH_AT = 20,
  anon_sym_SLASH_GT = 21,
  anon_sym_LBRACK_AT = 22,
  anon_sym_LBRACK_SLASH_AT = 23,
  anon_sym_SLASH_RBRACK = 24,
  sym_directive_name = 25,
  sym_directive_content = 26,
  sym_template = 27,
  sym_content = 28,
  sym_interpolation = 29,
  sym_comment = 30,
  sym_directive = 31,
  sym_angle_directive = 32,
  sym_square_directive = 33,
  sym_angle_user_directive = 34,
  sym_square_user_directive = 35,
  aux_sym_template_repeat1 = 36,
  aux_sym_content_repeat1 = 37,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_content_token1] = "content_token1",
  [anon_sym_LT] = "<",
  [anon_sym_LBRACK] = "[",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_DOLLAR_LBRACE] = "${",
  [anon_sym_RBRACE] = "}",
  [sym_expression] = "expression",
  [anon_sym_LT_POUND_DASH_DASH] = "<#--",
  [anon_sym_DASH_DASH_GT] = "-->",
  [anon_sym_LBRACK_POUND_DASH_DASH] = "[#--",
  [anon_sym_DASH_DASH_RBRACK] = "--]",
  [sym_comment_content] = "comment_content",
  [anon_sym_LT_POUND] = "<#",
  [anon_sym_LT_SLASH_POUND] = "</#",
  [anon_sym_GT] = ">",
  [anon_sym_LBRACK_POUND] = "[#",
  [anon_sym_LBRACK_SLASH_POUND] = "[/#",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LT_AT] = "<@",
  [anon_sym_LT_SLASH_AT] = "</@",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LBRACK_AT] = "[@",
  [anon_sym_LBRACK_SLASH_AT] = "[/@",
  [anon_sym_SLASH_RBRACK] = "/]",
  [sym_directive_name] = "directive_name",
  [sym_directive_content] = "directive_content",
  [sym_template] = "template",
  [sym_content] = "content",
  [sym_interpolation] = "interpolation",
  [sym_comment] = "comment",
  [sym_directive] = "directive",
  [sym_angle_directive] = "angle_directive",
  [sym_square_directive] = "square_directive",
  [sym_angle_user_directive] = "angle_user_directive",
  [sym_square_user_directive] = "square_user_directive",
  [aux_sym_template_repeat1] = "template_repeat1",
  [aux_sym_content_repeat1] = "content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_content_token1] = aux_sym_content_token1,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_DOLLAR_LBRACE] = anon_sym_DOLLAR_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_expression] = sym_expression,
  [anon_sym_LT_POUND_DASH_DASH] = anon_sym_LT_POUND_DASH_DASH,
  [anon_sym_DASH_DASH_GT] = anon_sym_DASH_DASH_GT,
  [anon_sym_LBRACK_POUND_DASH_DASH] = anon_sym_LBRACK_POUND_DASH_DASH,
  [anon_sym_DASH_DASH_RBRACK] = anon_sym_DASH_DASH_RBRACK,
  [sym_comment_content] = sym_comment_content,
  [anon_sym_LT_POUND] = anon_sym_LT_POUND,
  [anon_sym_LT_SLASH_POUND] = anon_sym_LT_SLASH_POUND,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LBRACK_POUND] = anon_sym_LBRACK_POUND,
  [anon_sym_LBRACK_SLASH_POUND] = anon_sym_LBRACK_SLASH_POUND,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LT_AT] = anon_sym_LT_AT,
  [anon_sym_LT_SLASH_AT] = anon_sym_LT_SLASH_AT,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LBRACK_AT] = anon_sym_LBRACK_AT,
  [anon_sym_LBRACK_SLASH_AT] = anon_sym_LBRACK_SLASH_AT,
  [anon_sym_SLASH_RBRACK] = anon_sym_SLASH_RBRACK,
  [sym_directive_name] = sym_directive_name,
  [sym_directive_content] = sym_directive_content,
  [sym_template] = sym_template,
  [sym_content] = sym_content,
  [sym_interpolation] = sym_interpolation,
  [sym_comment] = sym_comment,
  [sym_directive] = sym_directive,
  [sym_angle_directive] = sym_angle_directive,
  [sym_square_directive] = sym_square_directive,
  [sym_angle_user_directive] = sym_angle_user_directive,
  [sym_square_user_directive] = sym_square_user_directive,
  [aux_sym_template_repeat1] = aux_sym_template_repeat1,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_POUND_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_POUND_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_comment_content] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_SLASH_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK_SLASH_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_directive_name] = {
    .visible = true,
    .named = true,
  },
  [sym_directive_content] = {
    .visible = true,
    .named = true,
  },
  [sym_template] = {
    .visible = true,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_angle_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_square_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_angle_user_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_square_user_directive] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_template_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(16);
      ADVANCE_MAP(
        '$', 20,
        '-', 9,
        '/', 12,
        '<', 18,
        '>', 31,
        '[', 19,
        ']', 34,
        '}', 22,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 1:
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '@') ADVANCE(36);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(33);
      if (lookahead == '@') ADVANCE(39);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(24);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(26);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(6);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == ']') ADVANCE(27);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != ']') ADVANCE(28);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == '-') ADVANCE(5);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 11:
      if (lookahead == '/') ADVANCE(12);
      if (lookahead == '>') ADVANCE(31);
      if (lookahead == ']') ADVANCE(34);
      if (lookahead != 0) ADVANCE(42);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(37);
      if (lookahead == ']') ADVANCE(40);
      END_STATE();
    case 13:
      if (lookahead == '>') ADVANCE(25);
      if (lookahead == ']') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == '}') ADVANCE(22);
      if (lookahead != 0) ADVANCE(23);
      END_STATE();
    case 15:
      if (eof) ADVANCE(16);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '<') ADVANCE(18);
      if (lookahead == '[') ADVANCE(19);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_content_token1);
      if (lookahead != 0 &&
          lookahead != '$' &&
          lookahead != '<' &&
          lookahead != '[') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '/') ADVANCE(1);
      if (lookahead == '@') ADVANCE(35);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      if (lookahead == '#') ADVANCE(32);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '@') ADVANCE(38);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == '{') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLAR_LBRACE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_expression);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT_POUND_DASH_DASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_GT);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACK_POUND_DASH_DASH);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_RBRACK);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comment_content);
      if (lookahead == '-') ADVANCE(8);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_LT_POUND);
      if (lookahead == '-') ADVANCE(3);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_POUND);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_LBRACK_POUND);
      if (lookahead == '-') ADVANCE(4);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LBRACK_SLASH_POUND);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_LT_AT);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LT_SLASH_AT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LBRACK_AT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LBRACK_SLASH_AT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_SLASH_RBRACK);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_directive_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_directive_content);
      if (lookahead != 0 &&
          lookahead != '/' &&
          lookahead != '>' &&
          lookahead != ']') ADVANCE(42);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 15},
  [2] = {.lex_state = 15},
  [3] = {.lex_state = 15},
  [4] = {.lex_state = 15},
  [5] = {.lex_state = 15},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 15},
  [8] = {.lex_state = 15},
  [9] = {.lex_state = 15},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 15},
  [13] = {.lex_state = 15},
  [14] = {.lex_state = 15},
  [15] = {.lex_state = 15},
  [16] = {.lex_state = 15},
  [17] = {.lex_state = 15},
  [18] = {.lex_state = 15},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 10},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT_POUND_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK_POUND_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_RBRACK] = ACTIONS(1),
    [anon_sym_LT_POUND] = ACTIONS(1),
    [anon_sym_LT_SLASH_POUND] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LBRACK_POUND] = ACTIONS(1),
    [anon_sym_LBRACK_SLASH_POUND] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LT_AT] = ACTIONS(1),
    [anon_sym_LT_SLASH_AT] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LBRACK_AT] = ACTIONS(1),
    [anon_sym_LBRACK_SLASH_AT] = ACTIONS(1),
    [anon_sym_SLASH_RBRACK] = ACTIONS(1),
    [sym_directive_name] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_template] = STATE(29),
    [sym_content] = STATE(2),
    [sym_interpolation] = STATE(2),
    [sym_comment] = STATE(2),
    [sym_directive] = STATE(2),
    [sym_angle_directive] = STATE(8),
    [sym_square_directive] = STATE(8),
    [sym_angle_user_directive] = STATE(8),
    [sym_square_user_directive] = STATE(8),
    [aux_sym_template_repeat1] = STATE(2),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(9),
    [anon_sym_LT_POUND_DASH_DASH] = ACTIONS(11),
    [anon_sym_LBRACK_POUND_DASH_DASH] = ACTIONS(13),
    [anon_sym_LT_POUND] = ACTIONS(15),
    [anon_sym_LT_SLASH_POUND] = ACTIONS(17),
    [anon_sym_LBRACK_POUND] = ACTIONS(19),
    [anon_sym_LBRACK_SLASH_POUND] = ACTIONS(21),
    [anon_sym_LT_AT] = ACTIONS(23),
    [anon_sym_LT_SLASH_AT] = ACTIONS(23),
    [anon_sym_LBRACK_AT] = ACTIONS(25),
    [anon_sym_LBRACK_SLASH_AT] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym_content] = STATE(3),
    [sym_interpolation] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_angle_directive] = STATE(8),
    [sym_square_directive] = STATE(8),
    [sym_angle_user_directive] = STATE(8),
    [sym_square_user_directive] = STATE(8),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(27),
    [aux_sym_content_token1] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(9),
    [anon_sym_LT_POUND_DASH_DASH] = ACTIONS(11),
    [anon_sym_LBRACK_POUND_DASH_DASH] = ACTIONS(13),
    [anon_sym_LT_POUND] = ACTIONS(15),
    [anon_sym_LT_SLASH_POUND] = ACTIONS(17),
    [anon_sym_LBRACK_POUND] = ACTIONS(19),
    [anon_sym_LBRACK_SLASH_POUND] = ACTIONS(21),
    [anon_sym_LT_AT] = ACTIONS(23),
    [anon_sym_LT_SLASH_AT] = ACTIONS(23),
    [anon_sym_LBRACK_AT] = ACTIONS(25),
    [anon_sym_LBRACK_SLASH_AT] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym_content] = STATE(3),
    [sym_interpolation] = STATE(3),
    [sym_comment] = STATE(3),
    [sym_directive] = STATE(3),
    [sym_angle_directive] = STATE(8),
    [sym_square_directive] = STATE(8),
    [sym_angle_user_directive] = STATE(8),
    [sym_square_user_directive] = STATE(8),
    [aux_sym_template_repeat1] = STATE(3),
    [aux_sym_content_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(29),
    [aux_sym_content_token1] = ACTIONS(31),
    [anon_sym_LT] = ACTIONS(34),
    [anon_sym_LBRACK] = ACTIONS(34),
    [anon_sym_DOLLAR] = ACTIONS(34),
    [anon_sym_DOLLAR_LBRACE] = ACTIONS(37),
    [anon_sym_LT_POUND_DASH_DASH] = ACTIONS(40),
    [anon_sym_LBRACK_POUND_DASH_DASH] = ACTIONS(43),
    [anon_sym_LT_POUND] = ACTIONS(46),
    [anon_sym_LT_SLASH_POUND] = ACTIONS(49),
    [anon_sym_LBRACK_POUND] = ACTIONS(52),
    [anon_sym_LBRACK_SLASH_POUND] = ACTIONS(55),
    [anon_sym_LT_AT] = ACTIONS(58),
    [anon_sym_LT_SLASH_AT] = ACTIONS(58),
    [anon_sym_LBRACK_AT] = ACTIONS(61),
    [anon_sym_LBRACK_SLASH_AT] = ACTIONS(61),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(66), 1,
      aux_sym_content_token1,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(70), 2,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(68), 3,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
    ACTIONS(64), 10,
      ts_builtin_sym_end,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [28] = 5,
    ACTIONS(74), 1,
      aux_sym_content_token1,
    STATE(5), 1,
      aux_sym_content_repeat1,
    ACTIONS(80), 2,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(77), 3,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
    ACTIONS(72), 10,
      ts_builtin_sym_end,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [56] = 2,
    ACTIONS(84), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(82), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [77] = 2,
    ACTIONS(88), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(86), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [98] = 2,
    ACTIONS(92), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(90), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [119] = 2,
    ACTIONS(96), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(94), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [140] = 2,
    ACTIONS(100), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(98), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [161] = 2,
    ACTIONS(104), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(102), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [182] = 2,
    ACTIONS(108), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(106), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [203] = 2,
    ACTIONS(112), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(110), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [224] = 2,
    ACTIONS(116), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(114), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [245] = 2,
    ACTIONS(120), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(118), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [266] = 2,
    ACTIONS(124), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(122), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [287] = 2,
    ACTIONS(128), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(126), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [308] = 2,
    ACTIONS(132), 5,
      anon_sym_LT,
      anon_sym_LBRACK,
      anon_sym_DOLLAR,
      anon_sym_LT_POUND,
      anon_sym_LBRACK_POUND,
    ACTIONS(130), 11,
      ts_builtin_sym_end,
      aux_sym_content_token1,
      anon_sym_DOLLAR_LBRACE,
      anon_sym_LT_POUND_DASH_DASH,
      anon_sym_LBRACK_POUND_DASH_DASH,
      anon_sym_LT_SLASH_POUND,
      anon_sym_LBRACK_SLASH_POUND,
      anon_sym_LT_AT,
      anon_sym_LT_SLASH_AT,
      anon_sym_LBRACK_AT,
      anon_sym_LBRACK_SLASH_AT,
  [329] = 2,
    ACTIONS(136), 1,
      sym_directive_content,
    ACTIONS(134), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [337] = 2,
    ACTIONS(140), 1,
      sym_directive_content,
    ACTIONS(138), 2,
      anon_sym_RBRACK,
      anon_sym_SLASH_RBRACK,
  [345] = 2,
    ACTIONS(142), 1,
      anon_sym_RBRACK,
    ACTIONS(144), 1,
      sym_directive_content,
  [352] = 2,
    ACTIONS(146), 1,
      anon_sym_GT,
    ACTIONS(148), 1,
      sym_directive_content,
  [359] = 2,
    ACTIONS(150), 1,
      anon_sym_DASH_DASH_GT,
    ACTIONS(152), 1,
      sym_comment_content,
  [366] = 2,
    ACTIONS(154), 1,
      anon_sym_RBRACE,
    ACTIONS(156), 1,
      sym_expression,
  [373] = 1,
    ACTIONS(158), 2,
      anon_sym_RBRACK,
      anon_sym_SLASH_RBRACK,
  [378] = 1,
    ACTIONS(160), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [383] = 2,
    ACTIONS(150), 1,
      anon_sym_DASH_DASH_RBRACK,
    ACTIONS(162), 1,
      sym_comment_content,
  [390] = 1,
    ACTIONS(164), 1,
      sym_directive_name,
  [394] = 1,
    ACTIONS(166), 1,
      ts_builtin_sym_end,
  [398] = 1,
    ACTIONS(168), 1,
      anon_sym_DASH_DASH_GT,
  [402] = 1,
    ACTIONS(168), 1,
      anon_sym_DASH_DASH_RBRACK,
  [406] = 1,
    ACTIONS(170), 1,
      anon_sym_RBRACE,
  [410] = 1,
    ACTIONS(172), 1,
      sym_directive_name,
  [414] = 1,
    ACTIONS(174), 1,
      anon_sym_RBRACK,
  [418] = 1,
    ACTIONS(176), 1,
      sym_directive_name,
  [422] = 1,
    ACTIONS(178), 1,
      sym_directive_name,
  [426] = 1,
    ACTIONS(180), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 28,
  [SMALL_STATE(6)] = 56,
  [SMALL_STATE(7)] = 77,
  [SMALL_STATE(8)] = 98,
  [SMALL_STATE(9)] = 119,
  [SMALL_STATE(10)] = 140,
  [SMALL_STATE(11)] = 161,
  [SMALL_STATE(12)] = 182,
  [SMALL_STATE(13)] = 203,
  [SMALL_STATE(14)] = 224,
  [SMALL_STATE(15)] = 245,
  [SMALL_STATE(16)] = 266,
  [SMALL_STATE(17)] = 287,
  [SMALL_STATE(18)] = 308,
  [SMALL_STATE(19)] = 329,
  [SMALL_STATE(20)] = 337,
  [SMALL_STATE(21)] = 345,
  [SMALL_STATE(22)] = 352,
  [SMALL_STATE(23)] = 359,
  [SMALL_STATE(24)] = 366,
  [SMALL_STATE(25)] = 373,
  [SMALL_STATE(26)] = 378,
  [SMALL_STATE(27)] = 383,
  [SMALL_STATE(28)] = 390,
  [SMALL_STATE(29)] = 394,
  [SMALL_STATE(30)] = 398,
  [SMALL_STATE(31)] = 402,
  [SMALL_STATE(32)] = 406,
  [SMALL_STATE(33)] = 410,
  [SMALL_STATE(34)] = 414,
  [SMALL_STATE(35)] = 418,
  [SMALL_STATE(36)] = 422,
  [SMALL_STATE(37)] = 426,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_template_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_content_repeat1, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_square_directive, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_square_directive, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_angle_directive, 4, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_angle_directive, 4, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_square_user_directive, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_square_user_directive, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_angle_directive, 3, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_angle_directive, 3, 0, 0),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_angle_user_directive, 3, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_angle_user_directive, 3, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_square_directive, 4, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_square_directive, 4, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_angle_user_directive, 4, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_angle_user_directive, 4, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_square_user_directive, 4, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_square_user_directive, 4, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [166] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_freemarker(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "freemarker",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 25,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
