//https://learn.microsoft.com/en-us/sql/t-sql/functions/configuration-functions-transact-sql?view=sql-server-ver16
module.exports = {
  configuration_functions: $ => choice(
    $.datefirst_,
    $.dbts_,
    $.langid_,
    $.language_,
    $.lock_timeout_,
    $.max_connections_,
    $.max_precision_,
    $.nestlevel_,
    $.options_,
    $.remserver_,
    $.servername_,
    $.servicename_,
    $.spid_,
    $.textsize_,
    $.version_,
  ),

  datefirst_: $ => token('@@DATEFIRST'),
  dbts_: $ => token('@@DBTS'),
  langid_: $ => token('@@LANGID'),
  language_: $ => token('@@LANGUAGE'),
  lock_timeout_: $ => token('@@LOCK_TIMEOUT'),
  max_connections_: $ => token('@@MAX_CONNECTIONS'),
  max_precision_: $ => token('@@MAX_PRECISION'),
  nestlevel_: $ => token('@@NESTLEVEL'),
  options_: $ => token('@@OPTIONS'),
  remserver_: $ => token('@@REMSERVER'),
  servername_: $ => token('@@SERVERNAME'),
  servicename_: $ => token('@@SERVICENAME'),
  spid_: $ => token('@@SPID'),
  textsize_: $ => token('@@TEXTSIZE'),
  version_: $ => token('@@VERSION'),
};
